language: php
php:
- 7.1
sudo: false
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+?.*/"
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=koji.kuno@gmail.com
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=koji.kuno@gmail.com
  - WP_VERSION=latest WP_MULTISITE=0
cache:
  directories:
  - node_modules
  - vendor
install:
- nvm install 8
- npm install
- composer install
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- ls -la style.css index.php vendor/autoload.php
before_deploy:
- npm run zip
- ls -la oleinpress-media.zip
- export RELEASE_FILE=$(ls oleinpress-media.zip)
deploy:
  provider: releases
  api_key:
    secure: "dbi10um9nVfZWOWktACfaZ4XZMNswisESyp+QAS3kfwYFzrHL7CZHr17aLZZxjqNZ39GwTVP6vgIqaZKY5eBb9Tz3eW//1qUE66/GwDh0iDfcEfrGfYEfLdyYHDJ7js6QqogJzA8SGDl3+6k81/6s3FH7zD/vFwnMYMBbOp8SpWrc4gOMylcpAQIvAOQ1nyW/kQFiDn4lPRT9O+EUfRFp8Zv1aOucwAsRTUi2S0pfSX5HhcV7XDQ+L9UHn9jJ6F3dRCk21jmUTKdKHVMc2n8O5lZaG1SSPn3jnYBZlBG1n1pWe88vQAieaUmSpnQ8nIEXj0p/LuPax9NnWSseRNXnjToUODv+anmkytr+c4liQ0TvW8FmfFgegZgMIr+HZb5mF4huTbc9dIzeVcgbgXNgw3Ac2trjaTnvHJtKM65hRbyQbQZIoYYyqmtP2BGQZCrSeMJNXgywK5sw8qtZWe6O4KeZhp4aXnjoaqvAMBmjOwMMr88kLrwvkVHNsUf+Tt33b2RxR+KKsqIbPNF3CitW6PsREYs3flhoVbPyWC7K/aF+lTTDpPrnxjErA6TwbJOIz4mI+pasqbD7/Anl7aVfYbi5JZ1CddTnru9ti0dwcmPvDgX46KJuyDd5rjaSUdlnLwgnuSPKcB3aFmfGWLNj/Otg7OMOlUtHjL1IZ5/8KE="
  file: "${RELEASE_FILE}"
  on:
    tags: true
    repo: Olein-jp/OleinPress-Media
    php: 7.1
