language: php
php:
- 7.1
sudo: false
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+?.*/"
env:
  global:
  - GIT_COMMITTER_NAME=Olein-jp
  - GIT_COMMITTER_EMAIL=koji.kuno@gmail.com
  - GIT_AUTHOR_NAME=Olein-jp
  - GIT_AUTHOR_EMAIL=koji.kuno@gmail.com
  - WP_VERSION=latest WP_MULTISITE=0
cache:
  directories:
  - node_modules
  - vendor
install:
- nvm install 8
- npm install
- composer install
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- ls -la style.css index.php vendor/autoload.php
before_deploy:
- npm run zip
- ls -la oleinpress-media.zip
- export RELEASE_FILE=$(ls oleinpress-media.zip)

deploy:
  provider: releases
  api_key:
    secure: "fce131f829af4fdcee04fda630ac1b1f6a443b4c"
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
    repo: Olein-jp/OleinPress-Media
    php: 7.1
