language: php
php:
- 7.1
sudo: false
branches:
  only:
  - master
  - develop
  - "/\\d+\\.\\d+\\.\\d+?.*/"
env:
  global:
  - GIT_COMMITTER_NAME=Olein-jp
  - GIT_COMMITTER_EMAIL=koji.kuno@gmail.com
  - GIT_AUTHOR_NAME=Olein-jp
  - GIT_AUTHOR_EMAIL=koji.kuno@gmail.com
  - WP_VERSION=latest WP_MULTISITE=0
cache:
  directories:
  - node_modules
  - vendor
install:
- nvm install 8
- npm install
- composer install
before_script:
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
script:
- ls -la style.css index.php vendor/autoload.php
before_deploy:
- npm run zip
- ls -la oleinpress-media.zip
- export RELEASE_FILE=$(ls oleinpress-media.zip)

deploy:
  provider: releases
  api_key:
    secure: gaKuGaGTMFG4qcVj/n/YcXtI+7e8C4heJ9kojAEojiB6spsonqrJETydCzDlFOJ/0p5462qKaC88FJv3Ib3gPNNdjtYf1qm/gBKUa6TZTnfk1dO+5yI3bcduJb7TiWeTlDtlhS1lKcwm3reEILwa11+pjXrAtXK9Kex08C/xs4tP7sEW4QhhKzE63y2F531N22KjCl3h4li6Gca0skjUR9GfRiEgjp+WCCyzyLHsa5riVuWejg+/xcqubTuZRPFOiskoY+qONZ5vk98zP+cOm7izsebTrONt8B7JzkBDl+Cg7Q23CfKIFp1yxNjDtTvb/r5DPfb99P8YN0CVUlBXJEccvRqBqepaimUVzWpwI4K50RbZIL4tOESXxVraksLkZB/UKWUNzOsPYxj4aU1yEFEeOZV8xvZT+XZc/gc8nZCBzFeZHvecp6sLBi8Jt+3aLdd/w00FNboFrKowfws/QoThnT8oQ5C/XiVioHbYY2CWPn4t+LxAnGWH89uznQaIfpRs9o5rlcluJRXNOxOfxr+zRiTbgHDLGCHvanOuTf33KtEIqJTZz3ozVmXoUR3W4A4JH09cMu6q4bbdsnTmMEj0PIA5XEvzTpeMdp7IvzJiqwiVeL5olialgfU2h7pCFQ7KgDR9LNXq4HX8+9fGZqiYq2pKlPkFj3UUO5VKhAQ=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
    repo: Olein-jp/OleinPress-Media
    php: 7.1
